title: 'Adapt '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5412186
  brandStrength: 0.4938186234794557
  lightness: 0
  brandColors:
    - '#003374'
    - '#6585ac'
    - '#fe8358'
    - '#0acb80'
    - '#d1e6fb'
  rhythmicContrast: 0.265233
cta:
  bucket: null
  version: null
  domain: null
name: SarahBeardmore
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7562724
layout_spectrum: 0.52941
