name: SarahBeardmore
favicon: null
layout_spectrum: 0.52941
typography_spectrum: 0.58468
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#003374'
    - '#6585ac'
    - '#fe8358'
    - '#0acb80'
    - '#d1e6fb'
  brandStrength: 0.4938186234794557
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.945555473677814
purpose: []
